### ISSUE TITLE
Install halted at ERROR: Failed building wheel for pyBigWig

### ISSUE THREAD

**Issue by augustboyle** [mhorlacher/rbpnet#1]
Hello, I'm troubleshooting compiling but can't seem to resolve a failed pybigwig install.

If I use conda to install pybigwig, there are no issues, but when I try to use pip to install all the packages, I get this error.

It might have to do with curl on CentOS infrastructures:
Error in pybigwig install: `curl.h no such file or directory`
See https://stackoverflow.com/questions/11471690/curl-h-no-such-file-or-directory

I've looked into locally installing curl/curl-dev but I always have trouble with that sort of thing.

Any suggestions would be appreciated.

**Comment by mhorlacher** [comment]
Hi, I don't have a direct solution to the problem because so far I've only tested the package on Ubuntu, but perhaps you could try installing pyBigWig via conda (https://anaconda.org/bioconda/pybigwig) and with some luck the correct `curl.h` comes bundled with it. If not, you could try installing `curl`/`libcurl` via conda as well (https://anaconda.org/conda-forge/curl and https://anaconda.org/conda-forge/libcurl).

**Comment by augustboyle** [comment]
I didn't document completely everything I did but some combination of installing pybigwig and the rest of the dependencies with conda did allow the rbpnet commands to run.
