### ISSUE TITLE
peaks.crosslink bed generation from alignment files

### ISSUE THREAD

**Issue by dbogdano** [mhorlacher/rbpnet#4]
Hi Marc, 

Thanks for putting together RBPNet. Would you be able to provide some guidance on how to generate the example peaks.crosslink bed file and associated bigwig files used to create a tfrecord file? I tried running bedtools genomecov on the R2 reads from the ENCODE HepG2 PTBP1 data (hg38), with the -5 option for 5prime coverage, however the resulting file's coordinates do not match those in the example file.

Thanks again, 
Derek

**Comment by mhorlacher** [comment]
Dear Derek, thank you for your interest in this project. The `peaks.crosslink.chr19.bed` is merely for testing purposes in order to check whether the `rbpnet tfrecord` (and subsequently `rbpnet train`) work correctly. I've updated the example/data/ directory, which now contains a README.md with more detailed instructions on how to generate the tfrecord file. As for the bigWig, these were manually produced by 1) R2 reads were selected from the ENCODE BAM files with samtools flag `-f 128`, 2) R2 reads of both replicates were merged, 3) pileups were generated with bedtools genomecov using `-5` and `-3` for forward and reverse, respectively. 

Hope this helps, but let me know if some of these things were unclear or if you have other questions!

**Comment by dbogdano** [comment]
Hi Marc, 
Thanks for the quick reply and the updated repo. The added instructions are clear, I was able to process both the included example dataset and a few models of my own without any problems. 

Things appear to be running smoothly, so this issue can be closed. Thanks again ,
Derek

**Comment by mhorlacher** [comment]
Glad to hear that everything is running smoothly! Don't hesitate to open another issue if you encounter another problem.
