### ISSUE TITLE
Using uppercase sequences and lowercase sequences makes the results different

### ISSUE THREAD

**Issue by treblegaia** [mhorlacher/rbpnet#6]
hi, I just used the same sequences with different case, but I got really different results. Here are the command lines:
```
rbpnet predict --output {output.pred} --model {input.model} {input.upper.fa}
rbpnet predict --output {output.pred} --model {input.model} {input.lower.fa}
```

Then I visualized the results and got these:
![image](https://github.com/mhorlacher/rbpnet/assets/105196285/3ff6f460-7bae-4b47-8e83-07bf201d2bfb)
![image](https://github.com/mhorlacher/rbpnet/assets/105196285/f3fa25e0-b12a-4882-8a6b-e8ed060a6334)

How should I understand this result?

**Comment by mhorlacher** [comment]
Hi @treblegaia, you should convert all input sequences to upper-case, otherwise the model will not recognize the nucleotides and treat them as unknown. The model will map nucleotides to one-hot vectors, with A --> [1, 0, 0, 0] ... T --> [0, 0, 0, 1]. Unknown nucleotides will be mapped to a null-vector, i..e [0, 0, 0, 0]. So for a lower-case sequence, all nucleotides will be converted to the 'unknown' encoding. What you are seeing in the plot below is the bias of the model when all nucleotides in the input sequence are unknown.
